const $=s=>document.querySelector(s);let orders=[],selected=null;
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const money=n=>'Rp'+Number(n||0).toLocaleString('id-ID');
async function api(url,opt={}){const r=await fetch(url,{...opt,headers:{'Content-Type':'application/json',...(opt.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Request failed');return d}
function showDashboard(on){$('#login').classList.toggle('hidden',on);$('#dashboard').classList.toggle('hidden',!on)}
async function check(){try{const d=await api('/.netlify/functions/admin-session');if(d.authenticated){showDashboard(true);await load()}}catch{}}
async function login(){const msg=$('#loginMsg');msg.className='muted';msg.textContent='Logging in...';try{await api('/.netlify/functions/admin-login',{method:'POST',body:JSON.stringify({password:$('#password').value})});$('#password').value='';showDashboard(true);await load();msg.textContent=''}catch(e){msg.className='error';msg.textContent=e.message}}
function render(){const q=$('#search').value.trim().toLowerCase(),f=$('#filter').value;const rows=orders.filter(o=>(f==='ALL'||o.status===f)&&(`${o.orderId} ${o.customer?.name||''} ${o.customer?.whatsapp||''}`).toLowerCase().includes(q));$('#orders').innerHTML=rows.length?rows.map(o=>`<article class="order" data-s="${esc(o.status)}"><div><small>ORDER</small><br><strong>${esc(o.orderId)}</strong></div><div><small>CUSTOMER</small><br>${esc(o.customer?.name||'—')}</div><div><small>CONTACT</small><br>${esc(o.customer?.whatsapp||'—')}</div><div><small>TOTAL</small><br>${money(o.total)}</div><div><small>STATUS</small><br><span class="status" data-s="${esc(o.status)}">${esc(o.status)}</span></div><button class="open" data-open="${esc(o.orderId)}">OPEN</button></article>`).join(''):'<p class="muted">Tidak ada order.</p>';document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openDetail(b.dataset.open))}
function stats(s){$('#sTotal').textContent=s.total||0;$('#sPP').textContent=s.pendingPayment||0;$('#sPV').textContent=s.pendingVerification||0;$('#sPaid').textContent=s.paid||0;$('#sProc').textContent=s.processing||0;$('#sDone').textContent=s.completed||0}
async function load(){const d=await api('/.netlify/functions/admin-orders?ts='+Date.now());orders=d.orders||[];stats(d.stats||{});render();if(selected)openDetail(selected)}
function openDetail(id){const o=orders.find(x=>x.orderId===id);if(!o)return;selected=id;const items=(o.items||[]).map(i=>`<div class="item"><span>${esc(i.name)} ×${i.qty}</span><b>${money(i.price*i.qty)}</b></div>`).join('');const logs=(o.activityLog||[]).map(x=>`<div><b>${esc(x.action)}</b> · ${esc(x.actor)} · ${esc(x.timestamp)}${x.note?`<br>${esc(x.note)}`:''}</div>`).join('');$('#detail').classList.remove('hidden');$('#detail').innerHTML=`<div style="display:flex;justify-content:space-between;gap:10px;align-items:center"><div><small class="muted">ORDER DETAIL</small><h2 style="margin:6px 0">${esc(o.orderId)}</h2></div><button class="btn ghost" style="width:auto;margin:0" id="closeDetail">CLOSE</button></div><div class="detail-grid"><div class="kv"><span>CUSTOMER</span><b>${esc(o.customer?.name||'—')}</b></div><div class="kv"><span>WHATSAPP</span><b>${esc(o.customer?.whatsapp||'—')}</b></div><div class="kv"><span>INVOICE</span><b>${esc(o.invoiceId)}</b></div><div class="kv"><span>PAYMENT</span><b>${esc(o.paymentStatus)}</b></div><div class="kv"><span>ORDER STATUS</span><b>${esc(o.status)}</b></div><div class="kv"><span>CREATED</span><b>${esc(o.createdAt)}</b></div><div class="kv"><span>UPDATED</span><b>${esc(o.updatedAt)}</b></div></div><h3>PRODUCTS · ${money(o.total)}</h3><div class="items">${items||'<div class="muted">No items</div>'}</div>${o.proofUrl?`<h3>PAYMENT PROOF</h3><img class="proof" src="${esc(o.proofUrl)}" alt="Payment proof">`:'<p class="muted">Belum ada bukti pembayaran.</p>'}<div class="actions">${o.status==='PENDING VERIFICATION'?'<button class="btn hot" data-status="PAID">APPROVE PAYMENT</button><button class="btn danger" data-status="REJECTED">REJECT PAYMENT</button>':''}${o.status==='PAID'?'<button class="btn hot" data-status="PROCESSING">PROCESS ORDER</button>':''}${o.status==='PROCESSING'?'<button class="btn hot" data-status="COMPLETED">COMPLETE ORDER</button>':''}${o.status==='REJECTED'?'<button class="btn ghost" data-status="PENDING VERIFICATION">REOPEN REVIEW</button>':''}</div><h3>ACTIVITY LOG</h3><div class="log">${logs||'<div>No activity.</div>'}</div>`;$('#closeDetail').onclick=()=>$('#detail').classList.add('hidden');document.querySelectorAll('#detail [data-status]').forEach(b=>b.onclick=()=>changeStatus(id,b.dataset.status))}
async function changeStatus(id,status){const note=prompt('Catatan (opsional):')||'';try{await api('/.netlify/functions/admin-status',{method:'POST',body:JSON.stringify({orderId:id,status,note})});await load();openDetail(id)}catch(e){alert(e.message)}}
$('#loginBtn').onclick=login;$('#password').onkeydown=e=>{if(e.key==='Enter')login()};$('#refresh').onclick=load;$('#search').oninput=render;$('#filter').onchange=render;$('#logout').onclick=async()=>{await api('/.netlify/functions/admin-logout',{method:'POST'}).catch(()=>{});orders=[];showDashboard(false)};check();
